Update oke-connectivity.yaml

diff --git a/.github/workflows/oke-connectivity.yaml b/.github/workflows/oke-connectivity.yaml
--- a/.github/workflows/oke-connectivity.yaml
+++ b/.github/workflows/oke-connectivity.yaml
@@ -40,6 +40,12 @@ jobs:
     - name: Start Bastion Session and Connect to OKE Node
       run: |
        sudo apt-get install -y jq
+       # Validate SSH private key and extract public key
+        SSH_PUBLIC_KEY=$(ssh-keygen -y -f ~/.ssh/bastion_ssh_key 2>/dev/null)
+        if [[ -z "$SSH_PUBLIC_KEY" ]]; then
+         echo "ERROR: Invalid Bastion SSH private key."
+         exit 2
+        fi
        SESSION_ID=$(oci bastion session create \
        --bastion-id $BASTION_OCID \
        --target-resource-type "instance" \
